discord-bots: # num:token
  1: XXX
  2: XXX

discord-channels:
  1:
    bot: 1
    guild-id: 123456
    channel-id: 123456
    webhook-url: "https://discord.com/api/webhooks/123456/XXX"

qq-groups: # num:group-id
  1: 123456

forwards:
  -
    type: 0 # 0: 双向转发, 1: 仅 QQ -> Discord, 2: 仅 Discord -> QQ
    discord-channel: 1
    qq-group: 1
